"""Mock LLM API server for testing.

Provides a lightweight Flask app that mimics the OpenAI-compatible chat/completions
API. Returns fast, deterministic responses without any real LLM calls.

Can run standalone:
    python tests/mock_llm_server.py          # port 19999
    python tests/mock_llm_server.py 18888    # custom port

Or be imported and used as a fixture:
    from tests.mock_llm_server import create_mock_llm_app
"""
from __future__ import annotations

import json
import sys
import time
import uuid

from flask import Flask, Response, jsonify, request

# ── Canned responses per scenario ────────────────────────────────────

CANNED_RESPONSES = {
    # Default: short, friendly assistant reply
    "default": "Hello! I'm a mock assistant. How can I help you today?",
    # Thinking-enabled: includes reasoning
    "thinking": "The user asked a question. Let me think step by step about this.",
    # Tool call: returns a function call
    "tool_call": None,  # handled specially
    # Long response for streaming test
    "long": (
        "This is a longer response designed to test streaming. "
        "It contains multiple sentences that will be split into chunks. "
        "Each chunk simulates a token being generated by the LLM. "
        "The response includes **markdown formatting**, `code blocks`, "
        "and even some math: E = mc². "
        "This helps verify that the frontend renders streaming content correctly."
    ),
    # Endpoint mode: multi-turn worker+critic
    "endpoint_worker": (
        "I've analyzed the task and here's my implementation:\n\n"
        "```python\ndef solve(x):\n    return x * 2\n```\n\n"
        "This solution handles the core requirement."
    ),
    "endpoint_critic": (
        "The implementation looks correct. The function properly handles "
        "the input and returns the expected output. **Approved.**"
    ),
    # Swarm: master plan
    "swarm_plan": json.dumps({
        "agents": [
            {"id": "research-1", "role": "researcher", "objective": "Find information"},
            {"id": "coder-1", "role": "coder", "objective": "Write the code"},
        ]
    }),
    # Error scenario
    "error": None,  # triggers 500
}


def _detect_scenario(messages: list[dict], config: dict) -> str:
    """Detect which canned response to use based on request content."""
    if not messages:
        return "default"

    last_content = (messages[-1].get("content") or "").lower()

    # Explicit test triggers
    if "__test_error__" in last_content:
        return "error"
    if "__test_long__" in last_content:
        return "long"
    if "__test_tool__" in last_content:
        return "tool_call"
    if "__test_think__" in last_content:
        return "thinking"

    # Detect by config
    if config.get("endpointMode"):
        return "endpoint_worker"
    if config.get("swarmEnabled"):
        return "swarm_plan"

    return "default"


def _make_tool_call_response(model: str) -> dict:
    """Build a response with a tool call (web_search)."""
    return {
        "id": f"chatcmpl-mock-{uuid.uuid4().hex[:8]}",
        "object": "chat.completion",
        "created": int(time.time()),
        "model": model,
        "choices": [{
            "index": 0,
            "message": {
                "role": "assistant",
                "content": None,
                "tool_calls": [{
                    "id": f"call_mock_{uuid.uuid4().hex[:8]}",
                    "type": "function",
                    "function": {
                        "name": "web_search",
                        "arguments": json.dumps({"query": "test search query"})
                    }
                }]
            },
            "finish_reason": "tool_calls"
        }],
        "usage": {"prompt_tokens": 50, "completion_tokens": 10, "total_tokens": 60}
    }


def _make_completion_response(model: str, content: str,
                               thinking: str | None = None) -> dict:
    """Build a standard chat completion response."""
    msg = {"role": "assistant", "content": content}
    if thinking:
        msg["reasoning_content"] = thinking
    return {
        "id": f"chatcmpl-mock-{uuid.uuid4().hex[:8]}",
        "object": "chat.completion",
        "created": int(time.time()),
        "model": model,
        "choices": [{
            "index": 0,
            "message": msg,
            "finish_reason": "end_turn"
        }],
        "usage": {
            "prompt_tokens": 100,
            "completion_tokens": len(content.split()),
            "total_tokens": 100 + len(content.split()),
        }
    }


def _stream_response(model: str, content: str,
                      thinking: str | None = None):
    """Generate SSE stream for a chat completion."""
    chunk_id = f"chatcmpl-mock-{uuid.uuid4().hex[:8]}"

    # Optional thinking chunks
    if thinking:
        words = thinking.split()
        for i, word in enumerate(words):
            chunk = {
                "id": chunk_id,
                "object": "chat.completion.chunk",
                "created": int(time.time()),
                "model": model,
                "choices": [{
                    "index": 0,
                    "delta": {"reasoning_content": word + " "},
                    "finish_reason": None
                }]
            }
            yield f"data: {json.dumps(chunk)}\n\n"

    # Content chunks — stream word by word
    words = content.split()
    for i, word in enumerate(words):
        delta = {}
        if i == 0:
            delta["role"] = "assistant"
        delta["content"] = word + (" " if i < len(words) - 1 else "")

        chunk = {
            "id": chunk_id,
            "object": "chat.completion.chunk",
            "created": int(time.time()),
            "model": model,
            "choices": [{
                "index": 0,
                "delta": delta,
                "finish_reason": None
            }]
        }
        yield f"data: {json.dumps(chunk)}\n\n"

    # Final chunk with finish_reason
    final = {
        "id": chunk_id,
        "object": "chat.completion.chunk",
        "created": int(time.time()),
        "model": model,
        "choices": [{
            "index": 0,
            "delta": {},
            "finish_reason": "end_turn"
        }],
        "usage": {
            "prompt_tokens": 100,
            "completion_tokens": len(words),
            "total_tokens": 100 + len(words),
        }
    }
    yield f"data: {json.dumps(final)}\n\n"
    yield "data: [DONE]\n\n"


# ── Flask App ────────────────────────────────────────────────────────

def create_mock_llm_app() -> Flask:
    """Create a mock LLM API Flask app."""
    app = Flask(__name__)

    # Track request history for assertions
    app.request_history = []

    @app.route("/v1/chat/completions", methods=["POST"])
    def chat_completions():
        data = request.get_json(silent=True) or {}
        model = data.get("model", "mock-model")
        messages = data.get("messages", [])
        stream = data.get("stream", False)
        tools = data.get("tools")

        # Record for test assertions
        app.request_history.append({
            "timestamp": time.time(),
            "model": model,
            "messages": messages,
            "stream": stream,
            "tools": tools is not None,
        })

        # Detect scenario
        config = {}
        scenario = _detect_scenario(messages, config)

        # Error scenario
        if scenario == "error":
            return jsonify({"error": {"message": "Mock error", "type": "mock_error"}}), 500

        # Tool call scenario
        if scenario == "tool_call":
            if stream:
                # Tool calls in streaming mode
                resp_data = _make_tool_call_response(model)
                def gen_tool():
                    chunk = {
                        "id": resp_data["id"],
                        "object": "chat.completion.chunk",
                        "created": resp_data["created"],
                        "model": model,
                        "choices": [{
                            "index": 0,
                            "delta": resp_data["choices"][0]["message"],
                            "finish_reason": "tool_calls"
                        }]
                    }
                    yield f"data: {json.dumps(chunk)}\n\n"
                    yield "data: [DONE]\n\n"
                return Response(gen_tool(), mimetype="text/event-stream")
            return jsonify(resp_data)

        # Content scenarios
        content = CANNED_RESPONSES.get(scenario, CANNED_RESPONSES["default"])
        thinking = None
        if scenario == "thinking":
            thinking = CANNED_RESPONSES["thinking"]
            content = "After careful analysis, the answer is 42."

        if stream:
            return Response(
                _stream_response(model, content, thinking),
                mimetype="text/event-stream",
                headers={
                    "Cache-Control": "no-cache",
                    "X-Accel-Buffering": "no",
                }
            )
        return jsonify(_make_completion_response(model, content, thinking))

    @app.route("/v1/models", methods=["GET"])
    def list_models():
        return jsonify({
            "object": "list",
            "data": [
                {"id": "mock-claude", "object": "model", "owned_by": "mock"},
                {"id": "mock-gpt4", "object": "model", "owned_by": "mock"},
            ]
        })

    @app.route("/health", methods=["GET"])
    def health():
        return jsonify({"status": "ok", "requests_served": len(app.request_history)})

    return app


if __name__ == "__main__":
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 19999
    app = create_mock_llm_app()
    print(f"Mock LLM server running on http://127.0.0.1:{port}")
    print("  POST /v1/chat/completions — mock chat API")
    print("  GET  /v1/models           — model list")
    print("  GET  /health              — health check")
    app.run(host="127.0.0.1", port=port, debug=False)
