"""jsdom guard: the reading-experience rail (paper/reading_xp.js + the
report.js seams) distributes the v2 insight payload through the reader.

Drives the REAL shipped ``static/js/paper/report.js`` + ``paper/reading_xp.js``
under jsdom:

  • a view carrying ``_xpInsight`` (structured items with anchor_idx) renders
    connection / provocation cards right AFTER the anchored section heading —
    the index enumerates the same h2/h3 sequence the backend resolved against;
  • unanchored items + thesis/opinion/open problems rebuild the 💡 end section;
  • a 📦 recap card closes the report;
  • re-running the distribution is idempotent (no duplicate cards);
  • the v2 'insight' EVENT stashes the payload and distributes live WITHOUT
    appending the markdown block to fullText (legacy events still append);
  • the 'report_meta' event hot-swaps the finish tag with the secondPasses
    total + breakdown;
  • NEUTER: strip the after-render seam from report.js → no cards (the wiring
    is load-bearing), shipped file byte-identical after.

DB-free; skips cleanly when node + jsdom aren't installed.
"""

from __future__ import annotations

import os
import shutil
import subprocess

import pytest

pytestmark = pytest.mark.unit

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..'))
REPORT_JS = os.path.join(ROOT, 'static', 'js', 'paper', 'report.js')
XP_JS = os.path.join(ROOT, 'static', 'js', 'paper', 'reading_xp.js')
QA_JS = os.path.join(ROOT, 'static', 'js', 'paper', 'qa.js')
DEEPEN_JS = os.path.join(ROOT, 'static', 'js', 'paper', 'deepen.js')
NOTES_JS = os.path.join(ROOT, 'static', 'js', 'paper', 'notes.js')
FOCUS_JS = os.path.join(ROOT, 'static', 'js', 'paper', 'focus_mode.js')


def _node_deps_available() -> bool:
    if not shutil.which('node'):
        return False
    return os.path.isdir(os.path.join(ROOT, 'node_modules', 'jsdom'))


_HARNESS = r"""
const fs = require('fs');
const path = require('path');
const ROOT = process.argv[4];
const { JSDOM } = require(path.join(ROOT, 'node_modules', 'jsdom'));
const dom = new JSDOM('<!DOCTYPE html><body><div id="paperReportContent"></div></body>',
                      { url: 'http://localhost/' });
const win = dom.window;
global.window = win;
global.document = win.document;
global.localStorage = win.localStorage;
global.console = console;

win.escapeHtml = global.escapeHtml = (s) =>
  String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
win.t = global.t = (k, p) => {
  const TMPL = {
    'paper.xpConnTitle': 'Connections to your reading',
    'paper.xpProvTitle': 'Pause and think',
    'paper.xpRecapTitle': 'What you are taking away',
    'paper.xpCostBody': 'Report',
    'paper.xpPassInsight': 'Insight',
    'paper.xpPassTermfill': 'Glossary',
    'paper.finishCostTitle': 'Estimated cost of this generation',
    'paper.finishModelTitle': 'Model',
    'paper.finishTokensTitle': 'tokens',
    'paper.finishGeneratedBy': 'Generated by',
  };
  let s = (k in TMPL) ? TMPL[k] : k;
  if (p) for (const kk in p) s = s.replace(new RegExp('\\{' + kk + '\\}', 'g'), p[kk]);
  return s;
};
// A markdown stub that produces REAL headings (the distribution enumerates
// article h2/h3 — indices must match the backend's extract_report_headings).
win.renderMarkdown = global.renderMarkdown = (md) => {
  return String(md || '').split('\n').map((ln) => {
    if (ln.startsWith('### ')) return '<h3>' + escapeHtml(ln.slice(4)) + '</h3>';
    if (ln.startsWith('## ')) return '<h2>' + escapeHtml(ln.slice(3)) + '</h2>';
    if (ln.startsWith('# ')) return '<h1>' + escapeHtml(ln.slice(2)) + '</h1>';
    if (!ln.trim()) return '';
    return '<p>' + escapeHtml(ln) + '</p>';
  }).join('\n');
};
win.formatCny = global.formatCny = (v) => '¥' + Number(v).toFixed(4);
global._i18nLang = win._i18nLang = 'en';

eval(fs.readFileSync(process.argv[2], 'utf8'));  // real paper/report.js
eval(fs.readFileSync(process.argv[3], 'utf8'));  // real paper/reading_xp.js
eval(fs.readFileSync(process.argv[5], 'utf8'));  // real paper/qa.js
eval(fs.readFileSync(process.argv[6], 'utf8'));  // real paper/deepen.js
eval(fs.readFileSync(process.argv[7], 'utf8'));  // real paper/notes.js
eval(fs.readFileSync(process.argv[8], 'utf8'));  // real paper/focus_mode.js
const _realPaperAskQuestion = _paperAskQuestion;  // qa.js 真入口,§7 覆盖后 §8 恢复

// Capture the REAL glossary helpers before the stub block replaces them —
// §10 exercises the analogy column through the real implementation.
const _realExtractGlossary = _extractGlossary;
const _realDecorateGlossaryTerms = _decorateGlossaryTerms;

// Stub layout/enrichment helpers (jsdom has no layout; the functions under
// test run for real).
_decorateCallouts = () => {};
_frameFigures = () => {};
_decorateZoomableImages = () => {};
_decorateGlossaryTerms = () => {};
_extractGlossary = () => ({});
_indexHeadings = () => [];
_buildReportTOC = () => '';
_buildReadingTimeBar = () => null;
_wireReportScrollSpy = () => {};
_wireReadingTimeTracking = () => {};
_captureReadingAnchor = () => null;
_loadReadingPosition = () => null;
_restoreReadingAnchor = () => {};
_persistReadingPosition = () => {};
_syncReportToolbar = () => {};

const out = [];
function check(name, cond) { out.push((cond ? 'PASS ' : 'FAIL ') + name); }

const REPORT = [
  '# dUltra: Ultra-Fast Diffusion Decoding',
  '',
  '## TL;DR',
  'A fast diffusion LM.',
  '',
  '## Core Terminology',
  'terms',
  '',
  '## Method — How It Works',
  'The method section.',
  '',
  '## Experimental Analysis',
  'Numbers.',
].join('\n');

const ITEMS = {
  thesis: 'The paper bets that removing recurrence unlocks parallelism.',
  connections: [
    { kind: 'prior_paper', text: 'Same move as the Transformer.',
      paper: { title: 'Attention Is All You Need', arxiv_id: '1706.03762',
               abs_url: 'https://arxiv.org/abs/1706.03762' },
      anchor_idx: 2 },   // '## Method — How It Works'
    { kind: 'transfer', text: 'Transfers to your CAD-OCR problem.',
      paper: null, anchor_idx: null },   // unanchored → end section
  ],
  opinion: 'Bigger than its framing.',
  open_problems: [
    { text: 'Test at 100k-token context.', grounded_by: null },
  ],
  provocations: [
    { text: 'Is attention actually necessary?', anchor_idx: 3 },  // Experimental
    'a legacy string provocation',                                 // → end section
  ],
};

const view = (typeof _reportView === 'function') ? _reportView('report')
  : { kind: 'report', containerId: 'paperReportContent', meta: null,
      langKey: function () { return 'en'; } };
view._xpInsight = { items: ITEMS, markdown: '## 💡 Insight & Ideas\n' };
view.meta = { model: 'm1', costCny: 0.01 };

// ── (1) final render distributes anchored cards ──
const c = document.getElementById('paperReportContent');
_renderFinalReport(c, REPORT, { model: 'm1', costCny: 0.01 }, view);
const article = c.querySelector('.paper-report-article');
check('article_present', !!article);
const heads = article.querySelectorAll('h2, h3');
// The first four headings are the report's own h2s; the distributed end
// section appends its 💡 h2 + h3 subsections AFTER them.
check('headings_enumerated', heads.length >= 4
      && heads[0].textContent === 'TL;DR'
      && heads[1].textContent === 'Core Terminology'
      && heads[2].textContent === 'Method — How It Works'
      && heads[3].textContent === 'Experimental Analysis');
// The connection card (anchor_idx 2) must be the node right after heading 2.
const afterMethod = heads[2] && heads[2].nextElementSibling;
check('conn_card_after_anchored_heading',
      !!afterMethod && afterMethod.classList.contains('paper-xp-card')
      && afterMethod.classList.contains('xp-conn'));
check('conn_card_has_grounded_link',
      !!afterMethod && afterMethod.innerHTML.indexOf('arxiv.org/abs/1706.03762') !== -1);
// The provocation card (anchor_idx 3) after heading 3.
const afterExp = heads[3] && heads[3].nextElementSibling;
check('prov_card_after_anchored_heading',
      !!afterExp && afterExp.classList.contains('xp-prov'));
// Unanchored items rebuild the end section.
const endSec = article.querySelector('.paper-xp-section');
check('end_section_present', !!endSec);
check('end_section_has_unanchored_conn',
      !!endSec && endSec.innerHTML.indexOf('CAD-OCR') !== -1);
check('end_section_has_legacy_prov',
      !!endSec && endSec.innerHTML.indexOf('legacy string provocation') !== -1);
check('end_section_has_open_problem',
      !!endSec && endSec.innerHTML.indexOf('100k-token') !== -1);
// Recap card closes the report.
const recap = article.querySelector('.paper-xp-recap');
check('recap_present', !!recap);
check('recap_has_thesis',
      !!recap && recap.innerHTML.indexOf('removing recurrence') !== -1);
check('recap_has_open_problem',
      !!recap && recap.innerHTML.indexOf('100k-token') !== -1);

// ── (2) idempotent re-distribution ──
window._paperXpDistribute(article, view);
check('idempotent_single_conn_cards',
      article.querySelectorAll('.paper-xp-card.xp-conn').length === 1);
check('idempotent_single_recap',
      article.querySelectorAll('.paper-xp-recap').length === 1);

// ── (3) v2 insight EVENT: stash + live distribute, NO markdown append ──
const s = { kind: 'report', paperId: view.paperId || null, fullText: REPORT,
            toolRounds: [], _insightApplied: false };
const handled = window._paperXpHandleInsightEvent(s, {
  type: 'insight', insight: '## 💡 Insight & Ideas\n\nmarkdown body\n',
  items: ITEMS, baseline: 3.2 }, view);
check('v2_event_handled', handled === true);
check('v2_event_no_markdown_append', s.fullText === REPORT);
check('v2_event_stashed', !!(s._xpInsight && s._xpInsight.items));
// replay guard: second application does not double-insert
window._paperXpHandleInsightEvent(s, {
  type: 'insight', insight: 'x', items: ITEMS }, view);
check('v2_event_replay_guard',
      article.querySelectorAll('.paper-xp-card.xp-conn').length === 1);

// ── (4) legacy insight event (no items) → not handled by the rail ──
const s2 = { kind: 'report', fullText: REPORT, toolRounds: [], _insightApplied: false };
const handled2 = window._paperXpHandleInsightEvent(s2, {
  type: 'insight', insight: '## 💡 old block\n' }, view);
check('legacy_event_falls_through', handled2 === false);

// ── (5) report_meta event: finish tag hot-swap with secondPasses ──
const meta2 = { model: 'm1', costCny: 0.01, promptTokens: 1000, completionTokens: 200,
  totalCostCny: 0.015, totalCostUsd: 0.002,
  secondPasses: { insight: { fired: true, baseline: 3.2, costCny: 0.005,
                             usage: { prompt_tokens: 150, completion_tokens: 50 } } } };
const s3 = { kind: 'report', meta: { model: 'm1' } };
const mHandled = window._paperXpApplyMetaEvent(s3, { type: 'report_meta', meta: meta2 }, view);
check('report_meta_handled', mHandled === true);
check('report_meta_updates_view_meta', view.meta === meta2);
const tag = c.querySelector('.paper-report-finish-tag');
check('finish_tag_shows_total',
      !!tag && tag.innerHTML.indexOf('¥0.0150') !== -1);
check('finish_tag_breakdown_tooltip',
      !!tag && (tag.getAttribute('title') || tag.innerHTML).indexOf('Insight') !== -1);

// ── (6) cost breakdown builder ──
const bd = window._paperXpCostBreakdown(meta2);
check('breakdown_text', bd.indexOf('Report') !== -1 && bd.indexOf('Insight') !== -1);
check('breakdown_empty_without_passes', window._paperXpCostBreakdown({ model: 'm' }) === '');

// ── (7) P1: action buttons on cards ──
// NOTE: §2/§3 re-distributed, so §1's node refs are detached — re-query the
// LIVE tree (a click on a detached node never reaches the document listener).
const liveProvCard = article.querySelector('.paper-xp-card.xp-prov');
const provBtn = liveProvCard && liveProvCard.querySelector('.paper-xp-act.xp-act-debate');
check('prov_card_has_debate_btn', !!provBtn);
check('prov_btn_data_text',
      !!provBtn && provBtn.getAttribute('data-text') === 'Is attention actually necessary?');
// The open problem renders as an action card (not a markdown list item).
const openCard = article.querySelector('.paper-xp-section .paper-xp-card.xp-open');
check('open_problem_card_present', !!openCard);
const ideateBtn = openCard && openCard.querySelector('.paper-xp-act.xp-act-ideate');
check('open_card_has_ideate_btn', !!ideateBtn);
check('ideate_btn_data_text',
      !!ideateBtn && ideateBtn.getAttribute('data-text') === 'Test at 100k-token context.');
// Click routing: the document-level delegation routes debate → _paperAskQuestion
// and ideate → _startResearchJob.
const routed = [];
_paperAskQuestion = (t) => routed.push(['debate', t]);
_startResearchJob = (t) => routed.push(['ideate', t]);
provBtn.dispatchEvent(new win.MouseEvent('click', { bubbles: true }));
ideateBtn.dispatchEvent(new win.MouseEvent('click', { bubbles: true }));
check('debate_click_routes_to_qa',
      routed.length >= 1 && routed[0][0] === 'debate'
      && routed[0][1] === 'Is attention actually necessary?');
check('ideate_click_routes_to_research',
      routed.length >= 2 && routed[1][0] === 'ideate'
      && routed[1][1] === 'Test at 100k-token context.');

// ── (8) P1: _paperAskQuestion (real qa.js entry) seeds + sends ──
_paperAskQuestion = _realPaperAskQuestion;   // restore the real qa.js entry
global._paperActiveTab = 'report';   // paper-reader.js core state (not loaded)
const qaCalls = [];
const input = document.createElement('textarea');
input.id = 'paperQAInput';
document.body.appendChild(input);
_switchPaperTab = (tab) => qaCalls.push(['tab', tab]);
_setPaperMobileView = () => {};
_sendPaperQuestion = () => qaCalls.push(['send']);
// Run the deferred send synchronously.
const _st = global.setTimeout;
global.setTimeout = (f) => { f(); return 0; };
_paperAskQuestion('Is attention actually necessary?');
global.setTimeout = _st;
check('qa_entry_switches_tab', qaCalls.some((c) => c[0] === 'tab' && c[1] === 'qa'));
check('qa_entry_seeds_input',
      input.value === 'Is attention actually necessary?');
check('qa_entry_sends', qaCalls.some((c) => c[0] === 'send'));

// ── (9) P2: checkpoint flip cards at section ends ──
view._xpCheckpoints = { items: [
  { section: 'Method — How It Works', anchor_idx: 2,
    question: 'Why does removing recurrence unlock parallelism?',
    answer: 'Because the O(n) sequential dependency is gone.' },
  { section: 'Experimental Analysis', anchor_idx: 3,
    question: 'What does 54.2% mean?', answer: 'Resolve-rate on SWE-Bench Verified.' },
] };
window._paperXpDistributeCheckpoints(article, view);
const flips = article.querySelectorAll('.paper-xp-flip');
check('flip_cards_rendered', flips.length === 2);
// Section-end placement: the first flip sits between heading 2's section and
// heading 3 (i.e. right before the next h2/h3 in document order).
const flip1 = flips[0];
const nextAfterFlip = flip1 && flip1.nextElementSibling;
check('flip_card_at_section_end',
      !!nextAfterFlip && /^H[23]$/.test(nextAfterFlip.tagName || ''));
check('flip_front_shows_question',
      !!flip1 && flip1.querySelector('.paper-xp-flip-q')
      && flip1.querySelector('.paper-xp-flip-q').textContent.indexOf('removing recurrence') !== -1);
// Click flips to the answer face (document delegation).
flip1.dispatchEvent(new win.MouseEvent('click', { bubbles: true }));
check('flip_toggles', flip1.classList.contains('is-flipped'));
const backA = flip1.querySelector('.paper-xp-flip-a');
check('flip_back_has_answer',
      !!backA && backA.textContent.indexOf('O(n)') !== -1);
// Idempotent re-distribution.
window._paperXpDistributeCheckpoints(article, view);
check('flip_idempotent', article.querySelectorAll('.paper-xp-flip').length === 2);
// Live event: stash + distribute + replay guard.
const s4 = { kind: 'report' };
const cpHandled = window._paperXpHandleCheckpointsEvent(s4, {
  type: 'checkpoints', items: view._xpCheckpoints.items }, view);
check('checkpoints_event_handled', cpHandled === true && !!s4._xpCheckpoints);
check('checkpoints_replay_guard',
      window._paperXpHandleCheckpointsEvent(s4, {
        type: 'checkpoints', items: view._xpCheckpoints.items }, view) === true
      && article.querySelectorAll('.paper-xp-flip').length === 2);

// ── (10) P2: glossary analogy column → hover card ──
const gArt = document.createElement('article');
gArt.innerHTML =
  '<table><thead><tr><th>Term</th><th>Definition</th><th>Why</th><th>Analogy</th></tr></thead>' +
  '<tbody><tr><td>KV cache</td><td>Saved K/V tensors per layer.</td><td>Speed</td>' +
  '<td>leaving the meeting notes on the table</td></tr>' +
  '<tr><td>Dropout</td><td>Randomly zeroed activations.</td><td>Reg</td><td>—</td></tr>' +
  '</tbody></table>' +
  '<h2>Method</h2><p>The KV cache avoids recomputation. Dropout regularizes.</p>';
document.body.appendChild(gArt);
const gloss = _realExtractGlossary(gArt);
check('glossary_reads_analogy',
      gloss.length === 2 && gloss[0].analogy === 'leaving the meeting notes on the table');
check('glossary_dash_analogy_empty', gloss[1].analogy === '');
_realDecorateGlossaryTerms(gArt, gloss);
const termSpan = gArt.querySelector('.paper-term');
const anEl = termSpan && termSpan.querySelector('.paper-term-card-analogy');
check('hover_card_shows_analogy',
      !!anEl && anEl.textContent.indexOf('meeting notes') !== -1);
const spans = gArt.querySelectorAll('.paper-term');
let dropoutCard = null;
for (let si = 0; si < spans.length; si++) {
  if (spans[si].textContent.indexOf('Dropout') !== -1) dropoutCard = spans[si];
}
check('hover_card_without_analogy_when_dash',
      !!dropoutCard && !dropoutCard.querySelector('.paper-term-card-analogy'));
// Legacy 3-column table still works (analogy simply absent).
const g3 = document.createElement('article');
g3.innerHTML = '<table><thead><tr><th>Term</th><th>Def</th></tr></thead>' +
  '<tbody><tr><td>RL</td><td>Reward-driven learning.</td></tr></tbody></table>' +
  '<p>RL appears later.</p>';
document.body.appendChild(g3);
const gloss3 = _realExtractGlossary(g3);
check('legacy_3col_glossary_ok', gloss3.length === 1 && gloss3[0].analogy === '');

// ── (11) P2: skim mode (deterministic collapse) ──
// Re-render fresh (undo the flip/mutation state), then toggle skim on.
_renderFinalReport(c, REPORT, { model: 'm1' }, view);
const art2 = c.querySelector('.paper-report-article');
// Inject a blockquote callout into the Method section for the keep-check.
const heads2 = art2.querySelectorAll('h2');
let methodH = null;
for (let hi = 0; hi < heads2.length; hi++) {
  if (heads2[hi].textContent.indexOf('Method') !== -1) methodH = heads2[hi];
}
const bq = document.createElement('blockquote');
bq.textContent = 'Key takeaway: x';
methodH.insertAdjacentElement('afterend', bq);
// The section's REAL first prose paragraph (past the callout and any anchored
// xp card) — located BEFORE the figure paragraph lands, or the lookup would
// grab the figure itself.
let realFirstP = methodH.nextElementSibling;
while (realFirstP && realFirstP.tagName !== 'P') realFirstP = realFirstP.nextElementSibling;
// A FIGURE paragraph right after the callout: figures stay in skim AND must
// not consume the section's first-prose-paragraph budget.
const figP = document.createElement('p');
figP.innerHTML = '<img src="/api/paper/images/h/fig1.jpg">';
bq.insertAdjacentElement('afterend', figP);
// extraP lands after the real first paragraph.
const extraP = document.createElement('p');
extraP.textContent = 'second para should hide';
realFirstP.insertAdjacentElement('afterend', extraP);
// v3 skim (2026-08-06): a section that HAS prose collapses its detail — later
// paragraphs, tables and lists hide. (v2 kept them all; measured on the real
// report corpus that hid only 3–14% of characters — a visible no-op.)
const tbl = document.createElement('table');
tbl.innerHTML = '<tbody><tr><td>field</td><td>value</td></tr></tbody>';
extraP.insertAdjacentElement('afterend', tbl);
const ul = document.createElement('ul');
ul.innerHTML = '<li>choice A → because B</li>';
tbl.insertAdjacentElement('afterend', ul);
// Anti-blank guarantee (the v1 lesson): a section whose ONLY content is a
// table (Paper Card / Glossary shape) keeps it — never a bare heading.
const soloH = document.createElement('h2');
soloH.textContent = 'Solo Table Section';
const soloTbl = document.createElement('table');
soloTbl.innerHTML = '<tbody><tr><td>only</td><td>block</td></tr></tbody>';
art2.appendChild(soloH);
art2.appendChild(soloTbl);
_paperXpSkimToggle();
check('skim_on_class', c.classList.contains('paper-xp-skim-on'));
check('skim_hides_second_para', extraP.classList.contains('xp-skim-hidden'));
check('skim_keeps_blockquote', !bq.classList.contains('xp-skim-hidden'));
check('skim_hides_table', tbl.classList.contains('xp-skim-hidden'));
check('skim_hides_list', ul.classList.contains('xp-skim-hidden'));
check('skim_keeps_figure', !figP.classList.contains('xp-skim-hidden'));
check('skim_figure_preserves_first_para',
      !realFirstP.classList.contains('xp-skim-hidden'));
check('skim_anti_blank_keeps_solo_table',
      !soloTbl.classList.contains('xp-skim-hidden'));
check('skim_keeps_title',
      !art2.querySelector('h1').classList.contains('xp-skim-hidden'));
const methodFirstP = methodH.nextElementSibling;
check('skim_keeps_callout_first',
      methodFirstP === bq || !methodFirstP.classList.contains('xp-skim-hidden'));
// xp tutor cards stay visible in skim.
const skimConn = art2.querySelector('.paper-xp-card.xp-conn');
check('skim_keeps_xp_cards', !!skimConn && !skimConn.classList.contains('xp-skim-hidden'));
const skimBtn = document.querySelector('.paper-skim-btn');
// (button lives in index.html, absent in harness — toggle function tolerates)
_paperXpSkimToggle();
check('skim_off_restores',
      !c.classList.contains('paper-xp-skim-on')
      && !extraP.classList.contains('xp-skim-hidden')
      && !tbl.classList.contains('xp-skim-hidden'));

// ── (12) P3: deepen buttons + drawer (async) ──
(async () => {
  // Re-render fresh so the after-render seam injects the buttons.
  _renderFinalReport(c, REPORT, { model: 'm1' }, view);
  const art3 = c.querySelector('.paper-report-article');
  const deepBtns = art3.querySelectorAll('.paper-deepen-btn[data-mode="deeper"]');
  check('deepen_btns_per_report_heading', deepBtns.length === 4);
  // xp-internal headings (the 💡 end section) get NO deepen button.
  const xpSecH = art3.querySelector('.paper-xp-section h2, .paper-xp-section h3');
  check('xp_section_has_no_deepen_btn',
        !xpSecH || !xpSecH.querySelector('.paper-deepen-btn'));
  // Derive button on a display-math block, assigned to the containing section.
  const math = document.createElement('span');
  math.className = 'katex-display';
  const heads3 = art3.querySelectorAll('h2');
  heads3[2].insertAdjacentElement('afterend', math);
  window._paperDeepenAfterRender(art3, c, view);   // re-inject (idempotent)
  const deriveBtn = art3.querySelector('.paper-deepen-btn[data-mode="derive"]');
  check('derive_btn_on_math', !!deriveBtn);
  check('derive_btn_sec_idx',
        !!deriveBtn && deriveBtn.getAttribute('data-sec-idx') === '2');
  check('reinjection_idempotent',
        art3.querySelectorAll('.paper-deepen-btn[data-mode="deeper"]').length === 4);

  // Click → start → cached content renders instantly (no re-bill).
  global._paperHash = 'h-deepen';
  const calls = [];
  global.Api = win.Api = { paper: {
    deepenStart: async (body) => { calls.push(body);
      return { ok: true, cached: true, content: '## DEEP', usage: { prompt_tokens: 10, completion_tokens: 5 } }; },
    deepenPoll: async () => ({ ok: true, json: async () => ({ ok: true, events: [], status: 'done' }) }),
    deepenAbort: async () => ({}),
    reportCache: async () => ({ ok: true, meta: null }),
  } };
  // The re-injection above REPLACED the buttons — re-query live ones
  // (clicking a detached node never reaches the document listener).
  const liveBtns = art3.querySelectorAll('.paper-deepen-btn[data-mode="deeper"]');
  liveBtns[2].dispatchEvent(new win.MouseEvent('click', { bubbles: true }));
  await new Promise((r) => setTimeout(r, 20));
  check('deepen_start_params',
        calls.length === 1 && calls[0].section_idx === 2
        && calls[0].mode === 'deeper' && calls[0].paper_hash === 'h-deepen');
  const drawer = art3.querySelector('.paper-deepen-drawer');
  check('drawer_rendered_cached',
        !!drawer && drawer.innerHTML.indexOf('DEEP') !== -1);
  check('drawer_shows_usage',
        !!drawer && drawer.innerHTML.indexOf('tok') !== -1);
  // Second click toggles the drawer away (no double-bill).
  liveBtns[2].dispatchEvent(new win.MouseEvent('click', { bubbles: true }));
  await new Promise((r) => setTimeout(r, 20));
  check('second_click_closes_no_rebill',
        calls.length === 1 && !art3.querySelector('.paper-deepen-drawer'));

  // ── (13) P4: margin notes — decorate + editor flow ──
  global._paperHash = 'h-notes';
  const noteCalls = [];
  global.Api.paper.notesList = async () => ({ ok: true, notes: [] });
  global.Api.paper.notesCreate = async (body) => { noteCalls.push(['create', body]);
    return { ok: true, note: { id: 'pn_new1', paper_hash: body.paper_hash, lang: body.lang,
      anchor: body.anchor, note: body.note, created_at: 1, updated_at: 1 } }; };
  global.Api.paper.notesUpdate = async (id, text) => { noteCalls.push(['update', id, text]); };
  global.Api.paper.notesDelete = async (id) => { noteCalls.push(['delete', id]); };
  // Pre-seed BEFORE the render via the PRODUCTION write path (_paperXpSet
  // writes the store AND the instance — cross-_reportView-instance, exactly
  // what the cached-report code paths do) so the seam decorates directly.
  window._paperXpSet(view, '_paperNotes', [
    { id: 'pn_a', anchor: { heading_idx: 2, quote: 'The method section.' }, note: 'first note' },
    { id: 'pn_b', anchor: { heading_idx: 3, quote: 'zzz-no-such-text' }, note: 'chip note' },
    { id: 'pn_c', anchor: { heading_idx: null, quote: '' }, note: 'orphan note' },
  ]);
  _renderFinalReport(c, REPORT, { model: 'm1' }, view);
  const art4 = c.querySelector('.paper-report-article');
  const mark = art4.querySelector('.paper-note-mark');
  check('note_mark_wraps_quote', !!mark && mark.textContent.indexOf('method section') !== -1);
  check('note_mark_carries_id', !!mark && mark.getAttribute('data-note-id') === 'pn_a');
  const heads4 = art4.querySelectorAll('h2');
  const chip = heads4[3] && heads4[3].querySelector('.paper-note-chip');
  check('note_chip_on_heading', !!chip && chip.getAttribute('data-note-id') === 'pn_b');
  const tray = art4.querySelector('.paper-note-tray');
  check('note_orphan_tray', !!tray && tray.textContent.indexOf('orphan note') !== -1);
  // Idempotent re-decoration (marks unwrapped, not duplicated).
  _paperNotesDecorate(art4, view);
  check('note_decorate_idempotent',
        art4.querySelectorAll('.paper-note-mark').length === 1
        && art4.querySelectorAll('.paper-note-chip').length === 1);
  // Editor: open on the chip note, edit, save → notesUpdate + view sync.
  _paperNoteOpenEditor({ heading_idx: 3 }, view._paperNotes[1], 100, 100);
  const editor = document.querySelector('.paper-note-editor');
  check('note_editor_opens', !!editor);
  const ta = editor.querySelector('.paper-note-editor-input');
  ta.value = 'edited chip note';
  editor.querySelector('.paper-note-save').dispatchEvent(new win.MouseEvent('click', { bubbles: true }));
  await new Promise((r) => setTimeout(r, 20));
  check('note_update_called',
        noteCalls.some((c2) => c2[0] === 'update' && c2[1] === 'pn_b' && c2[2] === 'edited chip note'));
  check('note_view_synced', view._paperNotes[1].note === 'edited chip note');
  check('note_editor_closed', !document.querySelector('.paper-note-editor'));
  // Create flow: new note from an anchor → notesCreate + view grows.
  _paperNoteOpenEditor({ heading_idx: 1, quote: 'A fast diffusion LM.' }, null, 100, 100);
  const ed2 = document.querySelector('.paper-note-editor');
  ed2.querySelector('.paper-note-editor-input').value = 'brand new note';
  ed2.querySelector('.paper-note-save').dispatchEvent(new win.MouseEvent('click', { bubbles: true }));
  await new Promise((r) => setTimeout(r, 20));
  check('note_create_called',
        noteCalls.some((c2) => c2[0] === 'create' && c2[1].anchor.quote === 'A fast diffusion LM.'));
  // The create flow CONCATS → a NEW array replaces the store slot; read the
  // assertion through the store (the harness instance still points at the
  // old 3-item array — the very aliasing the store exists to survive).
  const notesAfterCreate = window._paperXpGet(view, '_paperNotes') || [];
  check('note_view_grew', notesAfterCreate.length === 4
        && notesAfterCreate[3].id === 'pn_new1');

  // ── (14) P4: focus mode ──
  // Viewport-anchored spotlight: with the scroller's top at 0 and the first
  // block scrolled out of view (rect above the edge), the current block must
  // be the FIRST one still visible — never pinned on the document title
  // (the old scrollTop=0 math did exactly that → "everything turned gray").
  const fkids = Array.prototype.slice.call(art4.children);
  fkids.forEach(function (el, i) {
    el.getBoundingClientRect = function () {
      return i === 0 ? { top: -200, bottom: -10 }
                     : { top: 10 + i * 20, bottom: 30 + i * 20 };
    };
  });
  _paperFocusModeToggle();
  check('focus_on_class', c.classList.contains('paper-focus-on'));
  const cur0 = art4.querySelector('.paper-focus-current');
  check('focus_has_current', !!cur0);
  check('focus_current_is_viewport_block',
        !!cur0 && Array.prototype.indexOf.call(art4.children, cur0) === 1);
  document.dispatchEvent(new win.KeyboardEvent('keydown', { key: 'j', bubbles: true }));
  const curIdx = (function () {
    const cur = art4.querySelector('.paper-focus-current');
    return cur ? Array.prototype.indexOf.call(art4.children, cur) : -1;
  })();
  check('focus_j_moves', curIdx > 0);
  document.dispatchEvent(new win.KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
  check('focus_esc_exits', !c.classList.contains('paper-focus-on'));
  // Skim interplay + H1 skip (2026-08-06): a skim-collapsed block leaves the
  // j/k flow; the bare H1 title never takes the OPENING spotlight (landing on
  // the title read as "everything just went gray" — owner report).
  art4.children[2].classList.add('xp-skim-hidden');
  fkids.forEach(function (el, i) {
    el.getBoundingClientRect = function () {
      return { top: 10 + i * 20, bottom: 30 + i * 20 };   // everything visible
    };
  });
  _paperFocusModeToggle();
  const curB = art4.querySelector('.paper-focus-current');
  const curBIdx = curB ? Array.prototype.indexOf.call(art4.children, curB) : -1;
  check('focus_never_opens_on_h1', curBIdx === 1);
  document.dispatchEvent(new win.KeyboardEvent('keydown', { key: 'j', bubbles: true }));
  const curC = art4.querySelector('.paper-focus-current');
  const curCIdx = curC ? Array.prototype.indexOf.call(art4.children, curC) : -1;
  check('focus_j_skips_skim_hidden', curCIdx === 3);
  document.dispatchEvent(new win.KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
  art4.children[2].classList.remove('xp-skim-hidden');

  // ── (15) P4: session summary toast ──
  const toasts = [];
  global.showToast = win.showToast = (m) => toasts.push(m);
  window._paperXpSessionSummary({ words: 300, minutes: 2.4 }, view);
  check('session_summary_fires', toasts.length === 1);
  check('session_summary_has_minutes', toasts[0].indexOf('2') !== -1);
  check('session_summary_has_notes', toasts[0].indexOf('4') !== -1);
  window._paperXpSessionSummary({ words: 0, minutes: 0 }, view);
  check('session_summary_skips_empty', toasts.length === 1);

  console.log(out.join('\n'));
  process.exit(0);
})();
"""


def _write_harness() -> str:
    harness = os.path.join(HERE, '_paper_reading_xp_harness.js')
    with open(harness, 'w', encoding='utf-8') as f:
        f.write(_HARNESS)
    return harness


def _run(report_js: str) -> subprocess.CompletedProcess:
    harness = _write_harness()
    try:
        return subprocess.run(['node', harness, report_js, XP_JS, ROOT, QA_JS,
                               DEEPEN_JS, NOTES_JS, FOCUS_JS],
                              capture_output=True, text=True, timeout=60)
    finally:
        try:
            os.remove(harness)
        except OSError:
            pass


@pytest.mark.skipif(not _node_deps_available(),
                    reason='node + jsdom dev-deps not installed (run npm install)')
def test_reading_xp_distribution_and_events():
    proc = _run(REPORT_JS)
    out = proc.stdout.strip()
    assert proc.returncode == 0, f'node failed: {proc.stderr}\n{out}'
    fails = [ln for ln in out.splitlines() if ln.startswith('FAIL')]
    assert not fails, 'reading-xp rail failures:\n' + out
    assert out.count('PASS') >= 75, f'expected >=75 PASS lines, got:\n{out}'


@pytest.mark.skipif(not _node_deps_available(),
                    reason='node + jsdom dev-deps not installed (run npm install)')
def test_after_render_seam_is_load_bearing():
    """NEUTER: strip the _paperXpAfterRender seam from _renderFinalReport →
    the cached-payload distribution no longer happens (cards absent), proving
    the seam (not some incidental render) is what surfaces anchored cards."""
    src = open(REPORT_JS, encoding='utf-8').read()
    marker = (
        "  if (typeof window._paperXpAfterRender === 'function') {\n"
        "    window._paperXpAfterRender(article, container, view);\n"
        "  }\n"
    )
    assert marker in src, 'after-render seam marker not found — test stale'
    patched = src.replace(marker, '', 1)
    tmp = os.path.join(HERE, '_paper_reading_xp_neuter.js')
    with open(tmp, 'w', encoding='utf-8') as f:
        f.write(patched)
    try:
        chk = subprocess.run(['node', '--check', tmp], capture_output=True, text=True, timeout=30)
        assert chk.returncode == 0, f'patched JS invalid: {chk.stderr}'
        proc = _run(tmp)
        out = proc.stdout.strip()
        assert proc.returncode == 0, f'node crashed: {proc.stderr}\n{out}'
        assert 'FAIL conn_card_after_anchored_heading' in out, \
            'NC: removing the seam did NOT stop the anchored distribution:\n' + out
        assert 'FAIL recap_present' in out, \
            'NC: removing the seam did NOT stop the recap card:\n' + out
    finally:
        try:
            os.remove(tmp)
        except OSError:
            pass
    assert open(REPORT_JS, encoding='utf-8').read() == src, 'shipped file was modified!'


if __name__ == '__main__':
    test_reading_xp_distribution_and_events()
    print('positive: PASS')
    test_after_render_seam_is_load_bearing()
    print('neuter: PASS')
    print('ALL PASSED')
