/* AUTO-GENERATED by scripts/gen_frontend_globals.py — DO NOT EDIT.
 *
 * Ambient declarations for the frontend's shared global scope. The bundle
 * (lib/js_bundler.py) concatenates every file into ONE scope with no module
 * wrapper, so these symbols really are globals at runtime; without this file
 * `tsc --checkJs` reports each cross-file reference as an undefined name and
 * the real bugs drown in the noise.
 *
 * DERIVED FROM THE SOURCE, never hand-maintained: rename or delete a symbol
 * and this file changes with it, so a stale declaration cannot outlive its
 * definition. Regenerate with:
 *
 *     python3 scripts/gen_frontend_globals.py
 *
 * tests/test_frontend_globals_generated.py runs --check in CI.
 *
 * Types are intentionally `any`: the goal is SYMBOL RESOLUTION (does this
 * name exist?), not describing the shapes. Precise types belong in JSDoc on
 * the definitions themselves.
 */

// ── Symbols exported via `window.X =` from inside an IIFE ──
// Private to their function scope (so tsc cannot see them) but public
// on the shared global object at runtime. Top-level names in BARE files
// are deliberately NOT listed: tsc already resolves those, and
// re-declaring them produces duplicate-identifier errors.
declare var Api: any;   // static/js/api.js
declare var ApiError: any;   // static/js/api.js
declare var Artifacts: any;   // static/js/artifacts.js
declare var BackendOfflineMonitor: any;   // static/js/core/backend_offline_monitor.js
declare var CHAT_EXCLUDED_CAPS_FALLBACK: any;   // static/js/core/model_caps.js
declare var ChipInput: any;   // static/js/widgets/chip_input.js
declare var CollabBar: any;   // static/js/presence.js
declare var ConvView: any;   // static/js/conv_view.js
declare var CookieCaptureConsent: any;   // static/js/cookie_capture_consent.js
declare var Icon: any;   // static/js/core/icons.js
declare var IconDot: any;   // static/js/core/icons.js
declare var LOGO_VER: any;   // static/js/core/brand_logo.js
declare var MODEL_HEALTH_STALE_AFTER_S: any;   // static/js/core/model_health.js
declare var ProjectBrain: any;   // static/js/project-brain.js
declare var ProjectBrainAttention: any;   // static/js/project-brain-attention.js
declare var ProjectBrainPeers: any;   // static/js/project-brain-peers.js
declare var ProjectBrainStatus: any;   // static/js/project-brain-status.js
declare var TofuPet: any;   // static/js/tofu-pet.js
declare var TofuScene: any;   // static/js/tofu-scene.js
declare var Voice: any;   // static/js/voice.js
declare var _ROUND_KEY_ORDER: any;   // static/js/ui/stream_reducer.js
declare var __RELAY_BILLING_ENABLED: any;   // static/js/relay-admin.js
declare var __RELAY_MODEL_ENABLED: any;   // static/js/relay-admin.js
declare var __fitCount: any;   // static/js/settings/providers/access_matrix.js
declare var __fitWork: any;   // static/js/settings/providers/access_matrix.js
declare var __presenceWired: any;   // static/js/presence.js
declare var __resizeCount: any;   // static/js/settings/providers/access_matrix.js
declare var __resizeEchoDropped: any;   // static/js/settings/providers/access_matrix.js
declare var __sse_test__: any;   // static/js/ui/sse_pipeline.js
declare var __swarmPushWired: any;   // static/js/ui/swarm_push.js
declare var __tofuCollectDiagnostics: any;   // static/js/diag_collect.js
declare var __tofuDiagRing: any;   // static/js/core/debug_panel.js
declare var __translatePushWired: any;   // static/js/translation.js
declare var _bootLoadInFlight: any;   // static/js/core/cross_tab_sync.js
declare var _bootReconnectStarted: any;   // static/js/main.js
declare var _browserClientId: any;   // static/js/local-control.js
declare var _canonRound: any;   // static/js/ui/stream_reducer.js
declare var _connToastState: any;   // static/js/ui/sse_poll_fallback.js
declare var _contextPolicy: any;   // static/js/main/main_toolbar_ui.js
declare var _currentUserId: any;   // static/js/core/current_user.js
declare var _cvOnLanguageChange: any;   // static/js/compaction-viewer.js
declare var _evRoundNum: any;   // static/js/ui/stream_reducer.js
declare var _finalizeProjection: any;   // static/js/ui/stream_reducer.js
declare var _isBootLoadHeld: any;   // static/js/core/cross_tab_sync.js
declare var _paperResponsiveOnCrossing: any;   // static/js/paper/pdf_responsive.js
declare var _pmModelDocCloseBound: any;   // static/js/paper/podcast.js
declare var _resolveContextLimit: any;   // static/js/context-bar.js
declare var _setOptimizerPanelOpen: any;   // static/js/optimizer.js
declare var _setTimerPanelOpen: any;   // static/js/timer.js
declare var _stampDeltaReset: any;   // static/js/ui/stream_reducer.js
declare var _streamRenderNoHighlight: any;   // static/js/ui/streaming_ui.js
declare var _swReconcileTicker: any;   // static/js/ui/streaming_swarm_panel.js
declare var _swTimerTicker: any;   // static/js/ui/streaming_swarm_panel.js
declare var _timerCountdownTicker: any;   // static/js/ui/tool_rounds.js
declare var _tofuProjectModalOpen: any;   // static/js/project.js
declare var _translationPolicy: any;   // static/js/main/main_toolbar_ui.js
declare var _uploadShrinkPolicy: any;   // static/js/main/main_toolbar_ui.js
declare var _vlmParseEntry: any;   // static/js/upload.js
declare var _welcomePillsHtml: any;   // static/js/core/icons.js
declare var applyCapabilityTaxonomy: any;   // static/js/core/model_caps.js
declare var applyLogoSkin: any;   // static/js/core/brand_logo.js
declare var applySectionRequirements: any;   // static/js/settings/section_requires.js
declare var attachCompactionMarkersToConversation: any;   // static/js/compaction-viewer.js
declare var brandLogoImgAttrs: any;   // static/js/core/brand_logo.js
declare var buildTurnCtxSnapshot: any;   // static/js/info-rail.js
declare var canonicalizeProjectionForCompare: any;   // static/js/ui/stream_reducer.js
declare var closeCompactionViewer: any;   // static/js/compaction-viewer.js
declare var closeProjectBrain: any;   // static/js/project-brain.js
declare var contextUsageSummary: any;   // static/js/context-bar.js
declare var defaultLogoUrl: any;   // static/js/core/brand_logo.js
declare var emptyStreamState: any;   // static/js/ui/stream_reducer.js
declare var flashGaugeForArchive: any;   // static/js/context-bar.js
declare var foldProbeHealth: any;   // static/js/core/model_health.js
declare var foldRuntimeHealth: any;   // static/js/core/model_health.js
declare var getChatExcludedCaps: any;   // static/js/core/model_caps.js
declare var getLogoSkin: any;   // static/js/core/brand_logo.js
declare var initNetLatency: any;   // static/js/net-latency.js
declare var initVoiceInput: any;   // static/js/voice.js
declare var isChatModel: any;   // static/js/core/model_caps.js
declare var listLogoSkins: any;   // static/js/core/brand_logo.js
declare var locateRound: any;   // static/js/ui/stream_reducer.js
declare var logoUrl: any;   // static/js/core/brand_logo.js
declare var modelGroupBrandNames: any;   // static/js/core/model_group.js
declare var modelGroupKey: any;   // static/js/core/model_group.js
declare var modelGroupLabel: any;   // static/js/core/model_group.js
declare var modelHealthLevelClass: any;   // static/js/core/model_health.js
declare var modelHealthUsable: any;   // static/js/core/model_health.js
declare var onBrandLogoError: any;   // static/js/core/brand_logo.js
declare var openCompactionViewer: any;   // static/js/compaction-viewer.js
declare var openMobileFlowPicker: any;   // static/js/mobile_panels.js
declare var openMobileOptimizer: any;   // static/js/mobile_panels.js
declare var openMobileTimer: any;   // static/js/mobile_panels.js
declare var openProjectBrain: any;   // static/js/project-brain.js
declare var openProjectBrainInfluence: any;   // static/js/project-brain.js
declare var presenceRefresh: any;   // static/js/presence.js
declare var projectBrainRefresh: any;   // static/js/project-brain.js
declare var projectColdSnapshot: any;   // static/js/ui/stream_reducer.js
declare var projectStreamEvents: any;   // static/js/ui/stream_reducer.js
declare var reconcileTurnCtxCapsule: any;   // static/js/info-rail.js
declare var reduceStreamState: any;   // static/js/ui/stream_reducer.js
declare var refreshMcpRailState: any;   // static/js/info-rail.js
declare var refreshRelayAdminTabs: any;   // static/js/relay-admin.js
declare var relayAdminCreateUser: any;   // static/js/relay-admin.js
declare var relayAdminMintCodes: any;   // static/js/relay-admin.js
declare var relayAdminSaveMargin: any;   // static/js/relay-admin.js
declare var relayAdminSwitch: any;   // static/js/relay-admin.js
declare var relayAdminToggleStatus: any;   // static/js/relay-admin.js
declare var relayAdminTopup: any;   // static/js/relay-admin.js
declare var relayAdminViewPayments: any;   // static/js/relay-admin.js
declare var renderTurnCtxNote: any;   // static/js/info-rail.js
declare var runManualCompaction: any;   // static/js/context-bar.js
declare var setLogoSkin: any;   // static/js/core/brand_logo.js
declare var toggleProjectBrain: any;   // static/js/project-brain.js
declare var toggleVoiceInput: any;   // static/js/voice.js
declare var updateContextBar: any;   // static/js/context-bar.js

// ── Runtime globals injected from OUTSIDE static/js ──
// Not discoverable by scanning that tree, so each is listed explicitly
// WITH the reason it is legitimately absent.
declare var TOFU_CONV_WINDOW: any;   // optional operator override read at runtime; never assigned in-tree
declare var _CONV_VERIFY_RETRY_DELAYS: any;   // test seam: a jsdom harness may shorten the verify backoff via this override
declare var __I18N_PACK_URLS__: any;   // injected by routes/common.py:559 as an inline <script> in the page shell
declare var _applyDebugModeVisibility: any;   // defined inline in index.html:2068 (loadFeatureFlags block)
declare var _applyTradingVisibility: any;   // defined inline in index.html next to _applyDebugModeVisibility; shows/hides the optional trading entry from the feature flag
declare var _waitForImageProcessing: any;   // defined in the deferred upload bundle; every call site is typeof-guarded

// ── window.<name> property access ──
// `declare var X` covers the bare reference; this covers `window.X`.
// Both spellings are in use, frequently for the same symbol.
interface Window {
  Api: any;
  ApiError: any;
  Artifacts: any;
  BackendOfflineMonitor: any;
  BackendOfflineMonitorProbeNow: any;
  BackendOfflineMonitorSnooze: any;
  CHATINNER_FURNITURE_IDS: any;
  CHAT_EXCLUDED_CAPS_FALLBACK: any;
  ChipInput: any;
  CollabBar: any;
  ConvView: any;
  CookieCaptureConsent: any;
  Icon: any;
  IconDot: any;
  LOGO_VER: any;
  MODEL_HEALTH_STALE_AFTER_S: any;
  ProjectBrain: any;
  ProjectBrainAttention: any;
  ProjectBrainI18n: any;
  ProjectBrainPeers: any;
  ProjectBrainStatus: any;
  TOFU_BP: any;
  TofuPet: any;
  TofuScene: any;
  Voice: any;
  _CHAT_MODE_DEFAULTS: any;
  _DEFERRED_ENTRY_POINTS: any;
  __RELAY_BILLING_ENABLED: any;
  __RELAY_MODEL_ENABLED: any;
  __fitCount: any;
  __fitWork: any;
  __presenceWired: any;
  __resizeCount: any;
  __resizeEchoDropped: any;
  __sse_test__: any;
  __swarmPushWired: any;
  __tofuCollectDiagnostics: any;
  __tofuDiagRing: any;
  __translatePushWired: any;
  _acquireBootLoad: any;
  _applyChatModeUI: any;
  _applyContinueCheckpoint: any;
  _applyHistoryRewrite: any;
  _applyImageGenAvailability: any;
  _applyPartialByRoundToSettled: any;
  _applyReaderPrefs: any;
  _bootLoadInFlight: any;
  _bootReconnectStarted: any;
  _browserClientId: any;
  _checkForQueuedTask: any;
  _classifyGhostTailJS: any;
  _clearPendingSyncMarkers: any;
  _collapseToolNames: any;
  _connToast: any;
  _connToastState: any;
  _contextPolicy: any;
  _currentUserId: any;
  _cvOnLanguageChange: any;
  _deriveChatModeFromFlags: any;
  _dispatchableQueueCount: any;
  _ephemeralToast: any;
  _flushPendingSyncs: any;
  _frameIsOurs: any;
  _hasImageGenModel: any;
  _hasRealToolRound: any;
  _hashStr: any;
  _isBootLoadHeld: any;
  _isErrorOnlyAssistant: any;
  _kickAutopilot: any;
  _lcBrowserDownload: any;
  _lcBrowserSetupState: any;
  _lcConnectLine: any;
  _lcPaintFloor: any;
  _lcRenderBrowser: any;
  _lcRenderDesktop: any;
  _lcSetAbout: any;
  _lcUpdateBadge: any;
  _loadFeatureBundle: any;
  _markStreamXlateFinal: any;
  _maskVuMachineTokens: any;
  _maybeArmAutopilot: any;
  _maybeAutoGenerateTitle: any;
  _mergeTerminalTurnFields: any;
  _mergeTranslationFields: any;
  _mobileCompactNow: any;
  _msgContentVersion: any;
  _msgElIndex: any;
  _msgFingerprint: any;
  _onConvSyncPush: any;
  _onFoldersChangedPush: any;
  _onReady: any;
  _paperResponsiveOnCrossing: any;
  _patchTranslateLoadingDom: any;
  _pmModelDocCloseBound: any;
  _prefetchConvCosts: any;
  _prefetchConvFileChanges: any;
  _privateHostAdd: any;
  _privateHostRemove: any;
  _privateHostToggle: any;
  _promptInjectMode: any;
  _promptRenameConversation: any;
  _raiseContinueShell: any;
  _readerFontStep: any;
  _readerWidthCycle: any;
  _rebaseUnackedTail: any;
  _refreshSystemPromptSummary: any;
  _rehydrateInjectRows: any;
  _releaseBootLoad: any;
  _removeStreamingVuBubbleIfTail: any;
  _renderMsgInPlace: any;
  _renderPrivateHosts: any;
  _renderStreamingTranslatePreview: any;
  _resolveContextLimit: any;
  _revalidateOnResume: any;
  _rollbackContinueShell: any;
  _runTerminalContinuation: any;
  _seedStreamTimerStart: any;
  _serverHasSegmentsLocalLacks: any;
  _serverHasTranslationLocalLacks: any;
  _setOptimizerPanelOpen: any;
  _setTimerPanelOpen: any;
  _spliceInjectRow: any;
  _stampLatestLiveTask: any;
  _startPendingSyncPolling: any;
  _streamRenderNoHighlight: any;
  _stripUsageTransient: any;
  _swReconcileTicker: any;
  _swTimerTicker: any;
  _timerCountdownTicker: any;
  _tofuProjectModalOpen: any;
  _translateFinalizeShouldDefer: any;
  _translationOnlyVerify: any;
  _translationPolicy: any;
  _trimMsgForPersist: any;
  _tsHasRealRound: any;
  _tsScanKeptRounds: any;
  _updateScrollToBottomBtn: any;
  _uploadShrinkPolicy: any;
  _vlmParseEntry: any;
  _warnModelCapsMissing: any;
  _watchQueuedDispatch: any;
  _welcomePillsHtml: any;
  _wireConvHistoryRewritePush: any;
  _wireConvSyncPush: any;
  _withInstantScroll: any;
  aiCompressLog: any;
  applyCapabilityTaxonomy: any;
  applyConvStateSnapshot: any;
  applyLogClean: any;
  applyLogoSkin: any;
  applyRunningTaskIdsFrame: any;
  applySectionRequirements: any;
  applySystemPromptEditor: any;
  applyToolsetNow: any;
  assertChatInnerOrder: any;
  assistantTailIsPriorTurn: any;
  attachCompactionMarkersToConversation: any;
  attachZipDropZone: any;
  brandLogoImgAttrs: any;
  buildSyncDigest: any;
  buildTurnCtxSnapshot: any;
  cancelAutopilotMarker: any;
  chatInnerHeadAnchor: any;
  chatInnerInsert: any;
  chatInnerOrderViolated: any;
  chatInnerOrderViolationSite: any;
  chatInnerTailAnchor: any;
  closeChatModeMenu: any;
  closeCompactionViewer: any;
  closeLocalControlModal: any;
  closeProjectBrain: any;
  closeSystemPromptEditor: any;
  computeConvBusy: any;
  computeTurnSettlement: any;
  contextUsageSummary: any;
  continueButtonForSettlement: any;
  convAutoTranslate: any;
  convAutoTranslateEffective: any;
  convHasMoreEarlier: any;
  convHasPendingSync: any;
  convTitleById: any;
  convWindowParam: any;
  defaultLogoUrl: any;
  detectLogNoise: any;
  dismissToolsetBanner: any;
  displayContent: any;
  distillFallbackDetail: any;
  emitMessageChanged: any;
  errorEnvelopeKind: any;
  errorEnvelopeMessage: any;
  fallbackCauseParts: any;
  fallbackKindLabel: any;
  finishLabelForSettlement: any;
  flashGaugeForArchive: any;
  flushIdentityGateDegraded: any;
  foldProbeHealth: any;
  foldRuntimeHealth: any;
  formatFileSize: any;
  getChatExcludedCaps: any;
  getLogoSkin: any;
  hideLogCleanBanner: any;
  hydrateFullConversation: any;
  identityGateDegraded: any;
  identityGateDegradedSite: any;
  initBackendOfflineMonitor: any;
  initCurrentUserId: any;
  initNetLatency: any;
  initVoiceInput: any;
  isChatModel: any;
  isDrawerViewport: any;
  isErrorEnvelope: any;
  isMobileViewport: any;
  isStalePartialTranslation: any;
  isTabletDrawerViewport: any;
  listLogoSkins: any;
  loadEarlierMessages: any;
  logoUrl: any;
  markConvPendingSync: any;
  markIdentityGateReported: any;
  mobileMediaQuery: any;
  modelGroupBrandNames: any;
  modelGroupKey: any;
  modelGroupLabel: any;
  modelHealthLevelClass: any;
  modelHealthUsable: any;
  needsTranslation: any;
  normalizeErrorEnvelope: any;
  onBrandLogoError: any;
  onProjectAttached: any;
  onProjectCleared: any;
  onToolsetDiverged: any;
  openCompactionViewer: any;
  openLocalControlModal: any;
  openMobileFlowPicker: any;
  openMobileOptimizer: any;
  openMobileTimer: any;
  openProjectBrain: any;
  openProjectBrainInfluence: any;
  openSettings: any;
  openSystemPromptEditor: any;
  pendingBusyStateSize: any;
  pickAuthoritativeTaskIdForReconnect: any;
  pollWriteWouldClobberSettledTail: any;
  prefersReducedMotion: any;
  presenceRefresh: any;
  previewLogClean: any;
  projectBrainRefresh: any;
  projectTranslation: any;
  readSSEStream: any;
  readTranslation: any;
  reconcileTurnCtxCapsule: any;
  recordWindowState: any;
  refreshInputSendHint: any;
  refreshMcpRailState: any;
  refreshRelayAdminTabs: any;
  relayAdminCreateUser: any;
  relayAdminMintCodes: any;
  relayAdminSaveMargin: any;
  relayAdminSwitch: any;
  relayAdminToggleStatus: any;
  relayAdminTopup: any;
  relayAdminViewPayments: any;
  renderErrorEnvelope: any;
  renderTranslateIndicator: any;
  renderTurnCtxNote: any;
  replayPendingBusyState: any;
  reportIdentityGateUnavailable: any;
  reportSyncDigest: any;
  resetChatInnerOrderForTests: any;
  resetCurrentUserIdForTests: any;
  resetIdentityGateWarnedForTests: any;
  resetPendingBusyStateForTests: any;
  resetSystemPromptBlocks: any;
  resolvePreference: any;
  runManualCompaction: any;
  runWithConcurrency: any;
  scrollChatToBottom: any;
  setChatMode: any;
  setLogoSkin: any;
  showAlert: any;
  showChoice: any;
  showConfirm: any;
  showLogCleanBanner: any;
  showPrompt: any;
  showToolsetApplyBanner: any;
  startSyncDriftProbe: any;
  streamHealthGet: any;
  streamHealthSubscribe: any;
  switchSettingsTab: any;
  syncToolsetBanner: any;
  tabletDrawerMediaQuery: any;
  toggleBrowserFromLocalModal: any;
  toggleChatModeMenu: any;
  toggleDesktopFromLocalModal: any;
  toggleOptimizerPanel: any;
  togglePendingQueueCollapsed: any;
  toggleProjectBrain: any;
  toggleTimerPanel: any;
  toggleVoiceInput: any;
  translateClaim: any;
  translateInflight: any;
  translateRelease: any;
  translationFingerprint: any;
  updateContextBar: any;
  updateMobileContext: any;
  wireConvWindowScrollLoader: any;
  TOFU_CONV_WINDOW: any;
  _CONV_VERIFY_RETRY_DELAYS: any;
  __I18N_PACK_URLS__: any;
  _applyDebugModeVisibility: any;
  _applyTradingVisibility: any;
  _waitForImageProcessing: any;
}
