# HOT_PATH
"""LLM-wire thumbnail downsizing for generated images.

Standalone submodule (no intra-package deps) — produces a shrunk (b64, mime)
copy of a full-res image for the chat-LLM message body, keeping wire bytes
under the gateway's ~4 MB cap.
"""

from __future__ import annotations

from lib.log import get_logger

logger = get_logger(__name__)

# ── LLM thumbnail constants ──
# The sankuai openresty gateway enforces a ~4 MB request body limit. A 2K PNG
# generated by gemini-3-pro-image-preview is ~12 MB raw (~16 MB base64 / ~15.7 MB
# after JSON serialization) — well over the cap, causing HTTP 413 at the gateway
# BEFORE the request reaches Claude. See memory `gateway-413-image-wire-size-fix`.
#
# Claude's vision tower internally downsamples anything to ≤1568 px on the long
# side before tokenization, so sending a 2K image wastes bytes that the model
# can't use anyway. We keep the full-res PNG on disk and in the project for the
# end user, but hand the chat LLM a downsized JPEG (or PNG for alpha) that is
# ~70× smaller on the wire.
_LLM_THUMB_MAX_PX = 1024
_LLM_THUMB_JPEG_QUALITY = 85


def _downsize_for_llm(image_b64: str, mime_type: str,
                      max_px: int = _LLM_THUMB_MAX_PX,
                      jpeg_quality: int = _LLM_THUMB_JPEG_QUALITY) -> tuple:
    """Return a downsized (b64, mime) copy suitable for LLM message bodies.

    Keeps the full-res copy caller-side for disk / project / history use;
    this function only produces a shrunk variant for the chat-LLM wire.

    Logic:
    - Resize so the longest side is ≤ ``max_px`` (LANCZOS).
    - Opaque images → re-encode as JPEG q=85 (tiny, lossy but visually fine).
    - Alpha-channel images → re-encode as PNG (preserves transparency).
    - If Pillow is unavailable or anything fails, return the original pair
      unchanged (caller decides whether to warn).

    Args:
        image_b64: Base64-encoded source image (no ``data:`` prefix).
        mime_type: Source MIME (``image/png`` / ``image/jpeg`` / ``image/webp``).
        max_px: Maximum longest-side pixel count for the downsized copy.
        jpeg_quality: JPEG quality (1-95) for opaque outputs.

    Returns:
        (b64_downsized, mime_downsized) — or (image_b64, mime_type) on any failure.
    """
    try:
        import base64 as _b64
        import io as _io

        from PIL import Image
    except Exception as e:
        logger.debug('[Tool:generate_image] Pillow unavailable, skipping downsize: %s', e)
        return image_b64, mime_type

    try:
        raw = _b64.b64decode(image_b64)
    except Exception as e:
        logger.warning('[Tool:generate_image] Downsize: b64 decode failed: %s', e)
        return image_b64, mime_type

    try:
        img = Image.open(_io.BytesIO(raw))
        img.load()
    except Exception as e:
        logger.warning('[Tool:generate_image] Downsize: PIL open failed: %s', e)
        return image_b64, mime_type

    w, h = img.size
    orig_bytes = len(raw)

    # ── Resize if oversized ──
    if max(w, h) > max_px:
        scale = max_px / float(max(w, h))
        new_w = max(1, int(round(w * scale)))
        new_h = max(1, int(round(h * scale)))
        try:
            img = img.resize((new_w, new_h), Image.LANCZOS)
        except Exception as e:
            logger.warning('[Tool:generate_image] Downsize: resize failed: %s', e)
            return image_b64, mime_type
    else:
        new_w, new_h = w, h

    # ── Detect real alpha (ignore degenerate RGBA where alpha is all 255) ──
    has_alpha = False
    if img.mode in ('RGBA', 'LA', 'PA'):
        try:
            alpha = img.getchannel('A')
            extrema = alpha.getextrema()  # (min, max)
            if extrema and extrema[0] < 255:
                has_alpha = True
        except Exception as e:
            logger.debug('[Tool:generate_image] Downsize: alpha probe failed: %s', e)
            has_alpha = True  # be safe, keep PNG

    buf = _io.BytesIO()
    try:
        if has_alpha:
            if img.mode != 'RGBA':
                img = img.convert('RGBA')
            img.save(buf, format='PNG', optimize=True)
            out_mime = 'image/png'
        else:
            if img.mode != 'RGB':
                img = img.convert('RGB')
            img.save(buf, format='JPEG', quality=jpeg_quality, optimize=True,
                     progressive=True)
            out_mime = 'image/jpeg'
    except Exception as e:
        logger.warning('[Tool:generate_image] Downsize: encode failed: %s', e)
        return image_b64, mime_type

    out_raw = buf.getvalue()
    # If downsizing somehow produced a LARGER payload (e.g. already tiny), keep original
    if len(out_raw) >= orig_bytes and (new_w, new_h) == (w, h):
        logger.debug('[Tool:generate_image] Downsize produced no savings (%d >= %d), keeping original',
                     len(out_raw), orig_bytes)
        return image_b64, mime_type

    out_b64 = _b64.b64encode(out_raw).decode('ascii')
    logger.info(
        '[Tool:generate_image] Downsized for LLM wire: %dx%d %s %d KB → %dx%d %s %d KB (%.1fx smaller)',
        w, h, mime_type, orig_bytes // 1024,
        new_w, new_h, out_mime, len(out_raw) // 1024,
        orig_bytes / max(len(out_raw), 1),
    )
    return out_b64, out_mime
