# Refactor Inventory — Redundancies & Decoupling Opportunities

_Generated by audit sweep; file:line citations point at the Definition sites._
_Action verbs: **merge** (collapse into one), **extract** (pull common code into a
helper/base), **split** (decompose a fat file), **keep** (same-name but semantically
distinct — annotate only, don't merge), **document** (note in a README or docstring)._

---

## 1. Search-engine boilerplate  →  **extract**

Four engines duplicate the same `requests.get(..., headers=HEADERS, timeout=12)` →
status handling → regex parse → `clean_text` → structured result list skeleton,
including near-identical `try/except Timeout/Exception + "[Search] X: N results in Ys"`
tail.

| Engine                                 | Definition                               |
|----------------------------------------|------------------------------------------|
| `search_bing`                          | `lib/search/engines/bing.py:47`          |
| `search_brave`                         | `lib/search/engines/brave.py:21`         |
| `search_ddg_html` / `search_ddg_api`   | `lib/search/engines/ddg.py:17` / `:72`   |
| `search_searxng`                       | `lib/search/engines/searxng.py:85`       |

**Action**: extract `http_search(url, params, parser, name, …)` in
`lib/search/_common.py` — Phase 1. Engines collapse to just the parser/URL quirks.

---

## 2. Thin tool handlers repeat log→time→call→meta  →  **extract**

Even with `_finalize_tool_round` + `_build_simple_meta` already in place, five thin
wrappers still repeat the "log call, `t0 = time.time()`, call `execute_*`, log
elapsed, build meta, finalize" boilerplate.

| Handler                 | Definition                                         |
|-------------------------|----------------------------------------------------|
| `_handle_scheduler_tool`| `lib/tasks_pkg/handlers/misc.py:103`               |
| `_handle_desktop_tool`  | `lib/tasks_pkg/handlers/misc.py:122`               |
| `_handle_conv_ref_tool` | `lib/tasks_pkg/handlers/misc.py:160`               |
| `_handle_swarm_tool`    | `lib/tasks_pkg/handlers/misc.py:140`               |
| `handle_mcp_tool`       | `lib/tasks_pkg/handlers/mcp.py:31`                 |

**Action**: add `simple_adapter(executor_fn, *, source, icon, badge_fn=None)` in
`lib/tasks_pkg/handlers/_adapter.py` — Phase 2.

---

## 3. Batch search/fetch handlers share a concurrency skeleton  →  **extract**

`_handle_web_search_batch` and `_handle_fetch_url_batch` are 99% the same
ThreadPoolExecutor pattern (preserve-order via `ordered[idx]`, exception
handling, char-budget truncation on concat).

| Handler                     | Definition                                       |
|-----------------------------|--------------------------------------------------|
| `_handle_web_search_batch`  | `lib/tasks_pkg/handlers/search.py:182`           |
| `_handle_fetch_url_batch`   | `lib/tasks_pkg/handlers/search.py:277`           |

**Action**: extract `run_batch_concurrent(items, worker, *, max_workers, ordered=True)`
in `lib/tasks_pkg/handlers/_adapter.py` — Phase 2.

---

## 4. Two `StrategyRegistry` classes — **KEEP (document)**

| Class                                              | Definition                                                       |
|----------------------------------------------------|------------------------------------------------------------------|
| `StrategyRegistry` (allocation weights)            | `lib/trading_strategy_engine/strategy.py:155`                    |
| `StrategyRegistry` (profile effectiveness tracking)| `lib/trading_autopilot/adaptive_decision_engine.py:137`          |

**Verdict**: they share a **name only**. Constructor signatures are incompatible
(`()` vs `(db)`), return types are different domains (`AllocationStrategy` vs
`StrategyProfile`), and no consumer uses them interchangeably. **Merging is not
safe** — it would break behavior.

**Action**: add a module-level `__all__` / docstring note at each site explaining
that the other class with the same name is intentionally distinct.

---

## 5. Two `StopLossManager` classes — **KEEP (document)**

| Class                                              | Definition                                              |
|----------------------------------------------------|---------------------------------------------------------|
| `StopLossManager` (rich: trailing+fixed+ATR+partial)| `lib/trading_risk.py:119`                              |
| `StopLossManager` (simpler, backtest-specific)     | `lib/trading_backtest_engine/state.py:44`               |

**Verdict**: different method names (`add_position`/`update` vs
`register`/`update`), different per-position dicts, different purpose (live
risk-manager vs backtest fast-path). A merge would be a semantic change, not a
refactor.

**Action**: annotate both files pointing at the other, and proceed only if the
user explicitly approves unification (§10.4 of CLAUDE.md).

---

## 6. `lib/swarm/compat.py`  ≠  `lib/compat.py` — **keep separate (document)**

Names collide but the contents are completely disjoint:

| File                   | Purpose                                                              |
|------------------------|----------------------------------------------------------------------|
| `lib/compat.py`        | Cross-platform compat (Linux/macOS/Windows shell, pipe I/O, /proc)   |
| `lib/swarm/compat.py`  | Backward-compat API wrapper for legacy `run_swarm_task()` / `_execute_wave()` |

**Action**: tighten the `lib/swarm/compat.py` module docstring so readers don't
think it's related to platform compat. No code change required.

---

## 7. Oversized modules  →  **split (deferred, see decomposition proposal)**

| File                              | LOC   | Action                                                              |
|-----------------------------------|-------|---------------------------------------------------------------------|
| `lib/llm_client.py`               | 3652  | split — body_builder / sse_stream / retry / dispatch                |
| `lib/tasks_pkg/compaction.py`     | 2620  | split — layers / token_budget / strategies                          |
| `routes/daily_report.py`          | 2669  | split — report_gen / prompts / scheduling / api                     |
| `routes/paper.py`                 | 2547  | split — upload / render / qa / translate / cache                    |
| `static/js/ui.js`                 | 8550  | split — messages / stream / tool_display / modals                   |
| `static/js/settings.js`           | 5569  | split — providers / models / features / ui                          |
| `static/js/main.js`               | 5417  | split — bootstrap / events / commands / streaming                   |
| `routes/chat.py`                  | 2172  | split — route layer / request adaptation / streaming (+ move helpers into lib) |
| `lib/tasks_pkg/orchestrator.py`   | 1899  | split — main loop / compaction bridge / finish handling             |
| `lib/tasks_pkg/manager.py`        | 1848  | split — task CRUD / event stream / persistence                      |
| `lib/tasks_pkg/tool_dispatch.py`  | 1726  | split — exec phase / abort / tool envelopes                         |
| `static/js/core.js`               | 3554  | split — network / state / helpers                                   |
| `routes/translate.py`             | 1309  | split — api / prompt / cache                                        |

See `docs/refactor_decomposition_proposal.md` for per-file breakdown. **All
entries in this table require user approval** before execution, per CLAUDE.md
§10.2/§10.3 (the fat modules touch model routing and task-manager invariants).

---

## 8. Other duplications spotted during audit — **document / deferred**

### 8a. Trading package sprawl
Four top-level trading packages with overlapping concerns:
`lib/trading/`, `lib/trading_autopilot/`, `lib/trading_backtest_engine/`,
`lib/trading_strategy_engine/`. A future pass could unify them under
`lib/trading/` with submodules, but this is a large reorganization affecting
many import sites — **ask first**.

### 8b. Tool handler registration convention
`handle_mcp_tool` uses monkey-patching of `tool_registry.lookup`
(`lib/tasks_pkg/handlers/mcp.py:97`) because MCP tool names are dynamic.
Could be cleaned up by adding a proper `register_fallback(predicate, handler)`
method to `ToolRegistry` — Phase 2 (minor).

### 8c. `ALLOCATION_STRATEGY` vs `AllocationStrategy`
`lib/trading_strategy_engine/portfolio.py:7` references
`StrategyRegistry` in its docstring but doesn't actually extend it. The two
modules are coupled by docstring only; consider centralizing the registry if
Phase 7a is ever executed.

### 8d. Fetch pattern replication
`fetch_urls` in `lib/fetch/core.py:410` uses its own ThreadPoolExecutor
scaffolding similar to the batch handlers in §3; but it serves a different
contract (dict return vs tuple stream) so no merge is proposed.

---

## 9. Items flagged but **NOT touched** (§10 — requires user approval)

- Retry caps, timeouts (`timeout=12` in search engines, 600s in swarm scheduler).
- `max_parallel=8` in `run_swarm_task`.
- `BATCH_CHAR_BUDGET = 300_000` in `_handle_fetch_url_batch`.
- Model routing tables in `lib/llm_dispatch/config.py`.

---

## Summary of Phase 1-4 actions taken

- Phase 1 (search engines): extract — **done in this pass**.
- Phase 2 (handler adapter + batch helper): extract — **done in this pass**.
- Phase 3 (StrategyRegistry / StopLossManager merge): **NOT done** — documented
  as semantically distinct (see §4, §5 above).
- Phase 4 (swarm compat dedup): **NOT a dedup** — different purposes
  (see §6 above); docstring clarified.
- Phase 5 (decomposition): doc-only, see
  `docs/refactor_decomposition_proposal.md`.
