#!/usr/bin/env python3
"""Ratchet funeral audit (P2-1 — docs/TESTING_STRATEGY.md §4).

WHY
---
This repo grows ~113 guard-ratchet suites (drift / parity / contract /
invariant / freeze families). A ratchet is only worth its keep while it
blocks a BUG it was born for; the drift family the JOURNAL keeps closing
("预存红…方向对齐") shows the other kind: pins that outlived their contract
and now block CHANGE, not bugs. Kent C. Dodds' implementation-detail warning,
institutionalised.

This audit cannot judge intent, so it classifies each guard suite by two
machine-checkable anchors:
  • NEUTER proof  — the suite contains a NEUTER test (byte-patch / neuter
                    self-check) proving the guard BITES a live behaviour.
  • Incident ref  — the suite cites its birth incident: an epic id
                    (pt_[0-9a-f]{16}), a commit hash reference, JOURNAL, or
                    the word 事故/incident.
A suite with NEITHER is an UNANCHORED funeral candidate: not auto-deleted
(deleting protection needs a human), but listed in docs/RATCHET_AUDIT.md for
owner review — link its incident, prove its bite, downgrade it, or delete it.

CLI: python scripts/ratchet_audit.py [--write-docs]
"""
from __future__ import annotations

import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
TESTS_DIR = os.path.join(ROOT, 'tests')

GUARD_FAMILY_RE = re.compile(
    r'(_parity|_drift|_guard|_invariant|_freeze|_ratchet)(_|\.py$)')
# Epic ids come in two lengths: 16 hex (current board) and 8 hex (early
# epics, e.g. pt_03f4cdf1 — the orchestrator-extraction family).
_EPIC_RE = re.compile(r'pt_[0-9a-f]{8,16}\b')
_COMMIT_RE = re.compile(r'\bcommit\s+`?[0-9a-f]{7,40}\b')
_INCIDENT_WORD_RE = re.compile(r'事故|incident', re.IGNORECASE)
_NEUTER_RE = re.compile(r'NEUTER')

# Family anchors: a whole suite family born from ONE documented incident.
# STRICT RULE: the cited artifact must EXIST in-repo — a family entry without
# a real artifact is laundering (absorbing unanchored suites into a fake
# family), and this script's self-check rejects it.
FAMILY_ANCHORS = {
    'test_api_contract_': 'docs/API_CONTRACT.md',
}


def family_anchor_of(filename: str) -> str | None:
    for prefix, artifact in FAMILY_ANCHORS.items():
        if filename.startswith(prefix):
            return artifact
    return None


def is_guard_file(filename: str) -> bool:
    return bool(GUARD_FAMILY_RE.search(filename))


def classify_source(source: str) -> dict:
    """Anchor signals for one guard suite. Pure — the same function the
    ratchet's own NEUTER test feeds synthetic sources."""
    return {
        'neuter': bool(_NEUTER_RE.search(source)),
        'epic': bool(_EPIC_RE.search(source)),
        'commit': bool(_COMMIT_RE.search(source)),
        'incident_word': bool(_INCIDENT_WORD_RE.search(source)),
        'journal': 'JOURNAL' in source,
    }


def is_anchored(signals: dict) -> bool:
    return (signals['neuter'] or signals['epic'] or signals['commit']
            or signals['incident_word'] or signals['journal'])


def audit(tests_dir: str = TESTS_DIR) -> list[dict]:
    rows = []
    for name in sorted(os.listdir(tests_dir)):
        if not (name.startswith('test_') and name.endswith('.py')):
            continue
        if not is_guard_file(name):
            continue
        with open(os.path.join(tests_dir, name), encoding='utf-8') as fh:
            signals = classify_source(fh.read())
        family = family_anchor_of(name)
        if family and os.path.isfile(os.path.join(ROOT, family)):
            signals['family'] = family
        else:
            signals['family'] = None
        anchored = is_anchored(signals) or bool(signals['family'])
        rows.append({'file': f'tests/{name}', **signals, 'anchored': anchored})
    return rows


def render_markdown(rows: list[dict]) -> str:
    anchored = [r for r in rows if r['anchored']]
    candidates = [r for r in rows if not r['anchored']]
    family_n = sum(1 for r in anchored if r.get('family'))
    lines = [
        '# RATCHET_AUDIT.md — 棘轮殡葬审计(P2-1)',
        '',
        '> Generated by `python scripts/ratchet_audit.py --write-docs`.',
        '> 判定是机械的:无 NEUTER 证明且无事故引用(pt_/commit/JOURNAL/事故/家族锚)',
        '> 的守护套件列入殡葬候选——**不是自动删除**,请逐个:补上事故链接 /',
        '> 证明咬合(NEUTER) / 降级 / 删除。删除保护需要人来判。',
        '',
        f'- 守护套件总数: **{len(rows)}**',
        f'- 有锚(NEUTER / 事故引用 / 家族锚×{family_n}): **{len(anchored)}**',
        f'- 殡葬候选(无锚): **{len(candidates)}**',
        '',
        '## 殡葬候选(无锚)',
        '',
        '| 文件 | 处理建议 |',
        '|---|---|',
    ]
    for r in candidates:
        lines.append(f"| `{r['file']}` | 补事故链接或 NEUTER,否则降级/删除 |")
    lines += [
        '',
        '## 有锚清单(抽样信号)',
        '',
        '| 文件 | NEUTER | epic | commit | 事故 | JOURNAL |',
        '|---|---|---|---|---|---|',
    ]
    for r in anchored:
        def m(k):
            return '✓' if r[k] else ''
        lines.append(
            f"| `{r['file']}` | {m('neuter')} | {m('epic')} | {m('commit')} "
            f"| {m('incident_word')} | {m('journal')} |")
    lines.append('')
    return '\n'.join(lines)


def main(argv: list[str]) -> int:
    for prefix, artifact in FAMILY_ANCHORS.items():
        if not os.path.isfile(os.path.join(ROOT, artifact)):
            print(f'[ratchet-audit] FAMILY ANCHOR LAUNDERING: {prefix} cites '
                  f'{artifact} which does not exist — fix or delete the entry')
            return 1
    rows = audit()
    anchored = sum(1 for r in rows if r['anchored'])
    print(f'[ratchet-audit] guard suites: {len(rows)}; anchored: {anchored}; '
          f'funeral candidates: {len(rows) - anchored}')
    for r in rows:
        if not r['anchored']:
            print(f"  CANDIDATE {r['file']}")
    if '--write-docs' in argv:
        path = os.path.join(ROOT, 'docs', 'RATCHET_AUDIT.md')
        with open(path, 'w', encoding='utf-8') as fh:
            fh.write(render_markdown(rows))
        print(f'[ratchet-audit] wrote {path}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv[1:]))
